[package]
name = "rusty_rogue"
version = "0.1.0"
authors = ["Erik Kirshey <ekirshey@gmail.com>"]

[dependencies]
chrono = "0.4"
rand = "0.5.4"

[features]
default = []

[dependencies.cursive]
version = "*"
default-features = false
features = ["pancurses-backend"]